### ISSUE TITLE
Godot 3.3.4 non existing function "save_to_string" in CryptoKey

### ISSUE THREAD

**Issue by Yesyoor** [fenix-hub/godot-engine.jwt#13]
The RS256 example does not work in Godot 3.3.4.
The CryptoKey class is missing the functions "save_to_string" and "load_from_string"

>>public_key.load_from_string(private_key.save_to_string(true))

Still, thanks for your work so far!

**Comment by fenix-hub** [comment]
Looks like in 3.5 they put back the `load_from_string` and `save_to_string` functions, so I'd recommend to use the most recent version, or just use [save](https://docs.godotengine.org/en/3.4/classes/class_cryptokey.html#class-cryptokey-method-save) and [load](https://docs.godotengine.org/en/3.4/classes/class_cryptokey.html#class-cryptokey-method-load) functions instead.
