### ISSUE TITLE
Invalid type in JWTDecoder function parse

### ISSUE THREAD

**Issue by AnasASK** [fenix-hub/godot-engine.jwt#14]
in JWTDecoder.gd:

```
func _init(jwt: String):
	self.parts = jwt.split(".")
	var header: PoolByteArray = JWTUtils.base64URL_decode(self.parts[0])
	var payload: PoolByteArray = JWTUtils.base64URL_decode(self.parts[1])
	self.header_claims = _parse_json(header)
	self.payload_claims = _parse_json(payload)

func _parse_json(field) -> Dictionary:
	var parse_result: JSONParseResult = JSON.parse(field)
	if parse_result.error != OK:
		return {}
	return parse_result.result
```

`JSON.parse(field)` field should be a string according to godot docs, but here a PoolByteArray is passed instead

**Comment by fenix-hub** [comment]
Looks like you are using a version from `dev` branch, try installing the plugin from `main` if you are using 3.x instead, or from `4.x` if you are using Godot 4.0 and later

**Comment by AnasASK** [comment]
I downloaded it from the releases, I will try installing from the master branch.

**Comment by fenix-hub** [comment]
Thanks, I forgot to make releases in a while, I'll make a new one just now so you can use it

**Comment by AnasASK** [comment]
Thanks it is working
