### ISSUE TITLE
Unable to verify using `with_any_of_issuers`

### ISSUE THREAD

**Issue by brownoxford** [fenix-hub/godot-engine.jwt#32]
# Bug report

## Describe the bug

The `JWTVerifier::verify_claims_values` function has the following block for verifying issuers, and does not take into account that the expected claim could be a `PackedStringArray` of issuers where only one must match.

```gdscript
JWTClaims.Public.ISSUER:
	if not jwt_decoder.get_issuer() == expected_claims.get(claim):
		self.exception = "The Claim 'iss' value doesn't match the required issuer."
		return false
```

## To Reproduce

```
	var jwt_verifier: JWTVerifier = (
		JWT
		. require(<an algorithm>)
		. with_any_of_issuers(["issuer a", "issuer b"])
		. build()
	)

	if jwt_verifier.verify(<a jwt>) != JWTVerifier.JWTExceptions.OK:
		print(jwt_verifier.exception)
		return false
```

This will crash with `Invalid operands 'String' and 'PackedStringArray' in operator '=='` because the `iss` claim in the JWT is actually a string, but even if that gets fixed the `==` comparison will require _all_ issuers specified, not _any_ issuer specified.

**Comment by chrisl8** [comment]
I tested this and it appears to work and does not cause any problem with existing usage.

**Comment by chrisl8** [comment]
This feature works now with the merge of that PR, but it also isn't documented.

I'm not sure if I feel like the right answer is to document it or to remove it. 😅 

I suppose I should look at the RFC an see if this is an expected JWT feature.
I would also understand if this was perhaps built to mirror another library, like a Java library, in which case it makes sense to maintain feature parity to make life easier on developers who are passing JWTs between applications written in different languages.

**Comment by fenix-hub** [comment]
Thank you all for your opinion.
We should definitely have a discussion about this - please feel free to open a new one in the dedicated section. It is very close to [the one opened](https://github.com/fenix-hub/godot-engine.jwt/discussions/43) by @brownoxford , so it's ok to continue that or open a new dedicated topic.
