### ISSUE TITLE
Invalid set index 'parts'

### ISSUE THREAD

**Issue by chrisl8** [fenix-hub/godot-engine.jwt#40]
I am getting the error `Invalid set index 'parts'` pointing to this line.

https://github.com/fenix-hub/godot-engine.jwt/blob/f7eba1bb91098ed231a9897ddbaa7c90db1095ee/addons/jwt/src/JWTDecoder.gd#L10

It appears that the `parts` variable was perhaps renamed to `_parts` but the usages were not updated?

EDIT: It looks to me like a lot of variables were renamed without their usage updated. It might be good to perform a test run on this code once before merging PRs? 😅 

P.S. I made a PR that gets it working again. Hope this helps, and again, thank you for all of the excellent work going on here!

**Comment by fenix-hub** [comment]
Thank you very much.
I'm rushing accepting PRs a little bit due to personal business, but I'm planning on reviewing everything during this weekend.
Also I make sure to design a github workflow to run some tests, following your suggestion.
Sorry about the invonvenience

**Comment by chrisl8** [comment]
> Thank you very much. I'm rushing accepting PRs a little bit due to personal business, but I'm planning on reviewing everything during this weekend. Also I make sure to design a github workflow to run some tests, following your suggestion. Sorry about the invonvenience

No worries. I'm even willing to test PRs if you need some extra eyes. I do appreciate this project, and I'm glad you are so open to input and updates. Moving fast and breaking things is fine.

**Comment by fenix-hub** [comment]
Thank you.
I would really appreciate an extra eye if you are willing to.
Actually my idea was to create a separate godot project with just the addon and some tests, and make it runnable inside a docker container.
This way we could directly add it in this repository as a github action ([ref](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)).
But just having this project in the first place and run it locally would be more than enough.
I'll make sure to handle the docker - github part then, since it's not much of a big deal for me. But I'm accepting suggestions and contributions on that part too of course.

**Comment by chrisl8** [comment]
> Thank you. I would really appreciate an extra eye if you are willing to. Actually my idea was to create a separate godot project with just the addon and some tests, and make it runnable inside a docker container. This way we could directly add it in this repository as a github action ([ref](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)). But just having this project in the first place and run it locally would be more than enough. I'll make sure to handle the docker - github part then, since it's not much of a big deal for me. But I'm accepting suggestions and contributions on that part too of course.

I watch this project so that I can update my code if it changes, so I can also try to test PRs and comment on them as I see them if I have a few days to catch them.

I do like the idea of a github action to run some basic tests. I haven't built such a thing yet that runs Godot, but in theory it should be possible. Sounds like a great idea to ensure the project always runs.

**Comment by brownoxford** [comment]
yikes, sorry about that!

**Comment by fenix-hub** [comment]
> I watch this project so that I can update my code if it changes, so I can also try to test PRs and comment on them as I see them if I have a few days to catch them.
> 
> I do like the idea of a github action to run some basic tests. I haven't built such a thing yet that runs Godot, but in theory it should be possible. Sounds like a great idea to ensure the project always runs.

Thank you very much for your support.
Ok if the idea of github actions sounds great to you too, I'll make sure to work on it and also share some insights and documentation here if you are interested. At least it is something we can all learn and improve together if it is helpful. But human reviews will always be necessary.


> yikes, sorry about that!

It's ok! 😄

**Comment by chrisl8** [comment]
This issue is fixed in main-godot4 now. Thank you!

**Comment by fenix-hub** [comment]
@chrisl8 https://github.com/fenix-hub/godot-engine.jwt/discussions/45#discussion-5975461

**Comment by fenix-hub** [comment]
@chrisl8 Ok, automated tests are now up and running!
